In [1]:
import numpy as np

# Création du tableau 1D
array1 = np.arange(10)

# Affichage du tableau
print(array1)


[0 1 2 3 4 5 6 7 8 9]


In [2]:
# Liste de nombres décimaux
liste = [3.14, 2.17, 0, 1, 2]

# Conversion en tableau NumPy d'entiers
array2 = np.array(liste, dtype=int)

# Affichage du tableau converti
print(array2)


[3 2 0 1 2]


In [3]:
# Création du tableau 3x3
array3 = np.arange(1, 10).reshape(3, 3)

# Affichage du tableau
print(array3)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Création d'un tableau 4x5 avec des valeurs aléatoires entre 0 et 1
array4 = np.random.rand(4, 5)

# Affichage du tableau
print(array4)


In [4]:
# Création d'un tableau 2D
array5 = np.array([[21, 22, 23, 22, 22], 
                   [20, 21, 22, 23, 24], 
                   [21, 22, 23, 22, 22]])

# Sélection de la 2e ligne (index 1)
row2 = array5[1]

# Affichage de la ligne sélectionnée
print(row2)


[20 21 22 23 24]


In [5]:
# Création du tableau 1D
array6 = np.arange(10)

# Inversion du tableau
reversed_array = array6[::-1]

# Affichage du tableau inversé
print(reversed_array)


[9 8 7 6 5 4 3 2 1 0]


In [6]:
# Création d'une matrice identité 4x4
identity_matrix = np.eye(4)

# Affichage de la matrice
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Création d'un tableau
array8 = np.arange(10)

# Calcul de la somme et de la moyenne
sum_val = np.sum(array8)
avg_val = np.mean(array8)

# Affichage des résultats
print(f"Somme : {sum_val}, Moyenne : {avg_val}")


Somme : 45, Moyenne : 4.5


In [10]:
# Création du tableau 1D
array9 = np.arange(1, 21)

# Reshape en 4x5
reshaped_array = array9.reshape(4, 5)

# Affichage du tableau remodifié
print(reshaped_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [11]:
# Création du tableau 1D
array10 = np.arange(10)

# Filtrage des nombres impairs
odd_numbers = array10[array10 % 2 == 1]

# Affichage des nombres impairs
print(odd_numbers)


[1 3 5 7 9]
